script: |
          # Refresh ECR auth for Docker
          aws ecr get-login-password --region eu-north-1 | \
          docker login --username AWS --password-stdin \
          ${{ secrets.ECR_REGISTORY }}

          # Refresh ECR secret for Kubernetes
          kubectl delete secret ecr-secret --ignore-not-found
          kubectl create secret docker-registry ecr-secret \
            --docker-server=${{ secrets.ECR_REGISTORY }} \
            --docker-username=AWS \
            --docker-password=$(aws ecr get-login-password --region eu-north-1)

          # Pull and deploy latest image
          docker pull ${{ secrets.ECR_REGISTORY }}/devops-final-project:latest
          kubectl set image deployment/devops-final-project \
          app=${{ secrets.ECR_REGISTORY }}/devops-final-project:latest
          kubectl rollout restart deployment/devops-final-project
          kubectl rollout status deployment/devops-final-project

          # Restart port-forward automatically
          pkill -f "kubectl port-forward" || true
          sleep 2
          nohup kubectl port-forward svc/devops-final-service 30080:3000 \
          --address 0.0.0.0 > /home/ubuntu/portforward.log 2>&1 &
          disown %1 2>/dev/null || true
          exit 0
        request_timeout: 120
        command_timeout: 30m
